require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'sky9' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'sky9Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
end

target 'sky9-tvOS' do
  # Pods for sky9-tvOS

  target 'sky9-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
